# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
inherit_from:
  - config/rubocop.yml
inherit_mode:
  merge:
    - Exclude
Metrics/AbcSize:
  Max: 90
Metrics/ClassLength:
  Max: 180

