default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: covid_19_zones_development
  username: covid_19_zones
  password: covid_19_zones
  host: localhost
  port: 5432


test:
  <<: *default
  database: covid_19_zones_test
  username: covid_19_zones
  password: covid_19_zones
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
