name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Install Bundler
      run: |
        gem install bundler
    - name: Install Gems
      run: |
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      run: |
        echo "bundle exec rails test goes here once we add pg"
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "covid-19-zones"
        HEROKU_LOGIN: "anshul@anshul.io"
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        bash .github/workflows/setup-heroku.sh
        heroku git:remote -a covid-19-zones
        git push -f heroku master
        heroku run rails db:migrate --app ${HEROKU_APP_NAME} --exit-code

